spring:
  application:
    name: eureka-cluster
  profiles:
    active: master
  security:
    user:
      name: admin
      password: admin

eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: false
    fetch-registry: false
---
spring:
  profiles: master

server:
  port: 8761

eureka:
  instance:
    hostname: master
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://admin:admin@slave1:8762/eureka/
---
spring:
  profiles: slave1

server:
  port: 8762

eureka:
  instance:
    hostname: slave1
    prefer-ip-address: false
  client:
    service-url:
      defaultZone: http://admin:admin@master:8761/eureka/